export const DATA = {
  id: {
    labels: ['Konteks & Masalah', 'Peran Saya', 'Cara Kerja', 'Hasil'],
    detail: [
      ['Setiap jenis usaha menjual dengan cara berbeda: F&B punya meja dan modifier, retail punya varian dan stok, laundry menghitung berat dan tanggal ambil. Sistem lama hanya mengenal satu alur, sehingga merchant di luar F&B memakai akal-akalan di luar sistem.', 'Product Owner — memimpin audit produk menyeluruh dan menyusun roadmap empat fase untuk POS multi-industri.', ['Menelusuri alur nyata di tiap jenis usaha: kasir dan dapur untuk F&B, stok dan varian untuk retail, penerimaan sampai pengambilan untuk laundry.', 'Memisahkan yang benar-benar umum (katalog, transaksi, cash shift) dari yang khusus per industri, sehingga inti produk tetap satu.', 'Menulis user story dengan acceptance criteria untuk katalog bervarian, layanan berbasis order, dan cash shift.'], 'Roadmap empat fase disetujui dengan satu inti POS yang melayani F&B, retail, laundry, dan UMKM lain, dipecah menjadi issue siap kerja di Linear.'],
      ['Calon pengantin memakai banyak alat terpisah: spreadsheet anggaran, grup chat untuk tamu, dan vendor undangan digital yang berbeda lagi.', 'Product Owner — discovery, problem statement, dan executive summary produk.', ['Mewawancarai calon pengguna untuk memisahkan kebutuhan perencanaan dan kebutuhan acara.', 'Menyatukan budget, timeline, dan guest list dengan undangan digital, RSVP, serta QR check-in dalam satu alur.', 'Menyusun prioritas rilis: perencanaan dulu, undangan menyusul.'], 'Executive summary dan problem statement disetujui sebagai dasar pembangunan produk, dengan scope rilis pertama yang jelas.'],
      ['Orang tua sulit memantau tugas harian anak, dan anak kehilangan motivasi karena tidak ada umpan balik yang terlihat.', 'Product Owner — definisi tujuan produk, mekanik gamifikasi, dan user story.', ['Menetapkan hasil yang diukur: konsistensi tugas selesai, bukan jumlah tugas dibuat.', 'Merancang mekanik apresiasi yang tidak berubah menjadi tekanan bagi anak.', 'Memisahkan peran orang tua dan anak menjadi dua alur aplikasi yang berbeda.'], 'Konsep produk dan backlog awal siap dikembangkan, dengan batasan gamifikasi yang disepakati bersama stakeholder.'],
      ['Pengelolaan keuangan pribadi tersebar di catatan manual, sehingga pengguna tidak tahu ke mana uangnya pergi setiap bulan.', 'Product Owner — konsep produk dan requirement awal untuk tim development.', ['Menyusun ide produk dan kebutuhan fitur inti: pencatatan, kategori, dan rencana anggaran.', 'Menuliskan requirement awal agar bisa langsung diestimasi.', 'Menyiapkan struktur backlog untuk iterasi pertama.'], 'Requirement awal diterima tim development sebagai dasar estimasi dan perencanaan sprint.'],
      ['Operasi logistik berjalan di beberapa sistem terpisah, membuat siklus lead sampai penagihan sulit dilacak.', 'Product Owner — backlog, roadmap, dan spesifikasi fungsional.', ['Memetakan siklus penuh lead → manifest → delivery → billing dan menandai titik putusnya.', 'Menyusun ulang backlog berdasarkan nilai bisnis bersama stakeholder operasional.', 'Menggunakan data dan query SQL untuk memvalidasi asumsi sebelum fitur dibangun.'], 'Perbaikan dirilis bertahap dengan siklus yang tertutup penuh, sehingga status pengiriman dan penagihan bisa dilacak dalam satu sistem.'],
      ['Merchant ingin menambah Google review tetapi tidak punya cara praktis meminta ulasan saat pelanggan masih di tempat.', 'Product Owner — definisi produk fisik, pricing, dan unit economics.', ['Memilih bentuk produk: kartu tap NFC dengan fallback QR untuk perangkat lama.', 'Menghitung biaya produksi per unit dan menetapkan struktur harga.', 'Menyiapkan rencana go-to-market untuk merchant kecil.'], 'Produk memiliki harga dan unit economics yang jelas, siap ditawarkan ke merchant sebagai paket berdiri sendiri.']
    ],
    projects: [
      ['Sistem POS', 'Sep 2026', 'screenshot Sistem POS', 'POS multi-industri untuk F&B, retail, laundry, dan UMKM lain: katalog, varian, stok, layanan berbasis order, dan cash shift. Memimpin audit penuh dan roadmap 4 fase.', ['Product Audit', 'Roadmapping', 'Process Mapping'], ['Linear', 'Figma', 'Miro', 'Notion']],
      ['WedPlanner Suite App', 'Agu 2026', 'screenshot WedPlanner', 'Wedding planning (budget, timeline, guest list) digabung undangan digital, RSVP, dan QR check-in. Menulis executive summary dan problem statement.', ['Product Discovery', 'Problem Framing', 'User Flow'], ['Linear', 'Figma', 'Notion']],
      ['KODOMO App', 'Agu 2026', 'screenshot KODOMO', 'Manajemen tugas orang tua–anak dengan gamifikasi disiplin: monitoring orang tua, rekam aktivitas anak, dan apresiasi.', ['Goal Definition', 'Gamifikasi', 'User Story'], ['Linear', 'Whimsical', 'Figma']],
      ['Financial Planner App', 'Jul 2026', 'screenshot Financial Planner', 'Konsep aplikasi manajemen keuangan personal: menyusun ide produk, kebutuhan fitur, dan requirement awal untuk tim development.', ['Product Concept', 'Requirement', 'Backlog'], ['Linear', 'Figma', 'Notion']],
      ['SaaS Logistics Platform', '2025 — 2026', 'screenshot Logistics', 'Improvement sistem manajemen logistik berbasis cloud, menutup siklus penuh dari lead → manifest → delivery → billing.', ['Backlog Management', 'Analisis Data', 'Spesifikasi Fungsional'], ['Jira', 'SQL', 'Notion']],
      ['Google Review Tap Card', 'Agu 2026', 'foto kartu NFC', 'Produk fisik kartu tap NFC/QR untuk membantu merchant mengumpulkan Google review. Mendefinisikan pricing dan unit economics.', ['Unit Economics', 'Pricing', 'Go-to-Market'], ['Notion', 'Excel', 'Canva']]
    ]
  },
  en: {
    labels: ['Context & Problem', 'My Role', 'How I Worked', 'Outcome'],
    detail: [
      ['Every trade sells differently: F&B has tables and modifiers, retail has variants and stock, laundry counts weight and pickup dates. The legacy system understood only one flow, so merchants outside F&B worked around it outside the system.', 'Product Owner — led a full product audit and built a four-phase roadmap for a multi-industry POS.', ['Traced the real flows in each trade: cashier and kitchen for F&B, stock and variants for retail, intake through pickup for laundry.', 'Separated what is genuinely shared (catalog, transactions, cash shift) from what is industry-specific, keeping one product core.', 'Wrote user stories with acceptance criteria for variant catalogs, order-based services, and cash shift.'], 'The four-phase roadmap was approved with a single POS core serving F&B, retail, laundry, and other small businesses, broken into ready-to-work Linear issues.'],
      ['Couples juggle separate tools: a budget spreadsheet, a chat group for guests, and a different vendor for digital invitations.', 'Product Owner — discovery, problem statement, and product executive summary.', ['Interviewed prospective users to separate planning needs from event-day needs.', 'Unified budget, timeline, and guest list with digital invitations, RSVP, and QR check-in in one flow.', 'Set release priority: planning first, invitations second.'], 'The executive summary and problem statement were approved as the basis for build, with a clear first-release scope.'],
      ['Parents struggle to track a child\'s daily tasks, and children lose motivation without visible feedback.', 'Product Owner — product goal definition, gamification mechanics, and user stories.', ['Defined the measured outcome as task consistency, not the number of tasks created.', 'Designed appreciation mechanics that do not turn into pressure on the child.', 'Split parent and child into two distinct in-app flows.'], 'Product concept and initial backlog ready for build, with gamification limits agreed with stakeholders.'],
      ['Personal finances live in scattered manual notes, so users cannot see where their money goes each month.', 'Product Owner — product concept and initial requirements for the development team.', ['Shaped the product idea and core feature needs: recording, categories, and budget planning.', 'Wrote initial requirements in a form the team could estimate directly.', 'Prepared the backlog structure for the first iteration.'], 'The development team accepted the initial requirements as the basis for estimation and sprint planning.'],
      ['Logistics operations ran across several separate systems, making the lead-to-billing cycle hard to trace.', 'Product Owner — backlog, roadmap, and functional specifications.', ['Mapped the full lead → manifest → delivery → billing cycle and marked where it broke.', 'Reordered the backlog against business value with operations stakeholders.', 'Used data and SQL queries to validate assumptions before features were built.'], 'Improvements shipped incrementally with the cycle fully closed, so delivery and billing status became traceable in one system.'],
      ['Merchants want more Google reviews but have no practical way to ask while the customer is still on site.', 'Product Owner — physical product definition, pricing, and unit economics.', ['Chose the product form: an NFC tap card with a QR fallback for older devices.', 'Calculated per-unit production cost and set the price structure.', 'Prepared a go-to-market plan for small merchants.'], 'The product has clear pricing and unit economics, ready to offer merchants as a standalone package.']
    ],
    projects: [
      ['POS System', 'Sep 2026', 'POS system screenshot', 'Multi-industry POS for F&B, retail, laundry, and other small businesses: catalog, variants, stock, order-based services, and cash shift. Led the full audit and a 4-phase roadmap.', ['Product Audit', 'Roadmapping', 'Process Mapping'], ['Linear', 'Figma', 'Miro', 'Notion']],
      ['WedPlanner Suite App', 'Aug 2026', 'WedPlanner screenshot', 'Wedding planning (budget, timeline, guest list) combined with digital invitations, RSVP and QR check-in. Wrote the executive summary and problem statement.', ['Product Discovery', 'Problem Framing', 'User Flow'], ['Linear', 'Figma', 'Notion']],
      ['KODOMO App', 'Aug 2026', 'KODOMO screenshot', 'Parent–child task management with discipline gamification: parent monitoring, child activity record, and appreciation.', ['Goal Definition', 'Gamification', 'User Story'], ['Linear', 'Whimsical', 'Figma']],
      ['Financial Planner App', 'Jul 2026', 'Financial Planner screenshot', 'Personal financial management app concept: product idea, feature needs, and initial requirements for the development team.', ['Product Concept', 'Requirements', 'Backlog'], ['Linear', 'Figma', 'Notion']],
      ['SaaS Logistics Platform', '2025 — 2026', 'Logistics screenshot', 'Improvements to a cloud logistics management system covering the full cycle from lead → manifest → delivery → billing.', ['Backlog Management', 'Data Analysis', 'Functional Spec'], ['Jira', 'SQL', 'Notion']],
      ['Google Review Tap Card', 'Aug 2026', 'NFC card photo', 'Physical NFC/QR tap card helping merchants collect Google reviews. Defined pricing and unit economics.', ['Unit Economics', 'Pricing', 'Go-to-Market'], ['Notion', 'Excel', 'Canva']]
    ]
  }
};
export const UI = {
  id: { back: 'Kembali ke portfolio', crumb: 'Proyek', role: 'Product Owner', other: 'Proyek lainnya', toolsLbl: 'TOOLS', skillLbl: 'SKILL' },
  en: { back: 'Back to portfolio', crumb: 'Projects', role: 'Product Owner', other: 'Other projects', toolsLbl: 'TOOLS', skillLbl: 'SKILLS' }
};
